// Code generated by reinforcer, DO NOT EDIT.

package reinforced

// ClientMethods are the methods in Client
var ClientMethods = struct {
	GenerateGreeting string
	SayHello         string
}{
	GenerateGreeting: "GenerateGreeting",
	SayHello:         "SayHello",
}

// SomeOtherClientMethods are the methods in SomeOtherClient
var SomeOtherClientMethods = struct {
	DoStuff string
}{
	DoStuff: "DoStuff",
}
