// Code generated by reinforcer, DO NOT EDIT.

package reinforced

// ClientMethods are the methods in Client
var ClientMethods = struct {
	GenerateGreeting string
	SayHello         string
}{
	GenerateGreeting: "GenerateGreeting",
	SayHello:         "SayHello",
}

// SomeOtherClientMethods are the methods in SomeOtherClient
var SomeOtherClientMethods = struct {
	DoStuff            string
	GetUser            string
	MethodWithChannel  string
	MethodWithWildcard string
	SaveFile           string
}{
	DoStuff:            "DoStuff",
	GetUser:            "GetUser",
	MethodWithChannel:  "MethodWithChannel",
	MethodWithWildcard: "MethodWithWildcard",
	SaveFile:           "SaveFile",
}
