// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	generator "github.com/csueiras/reinforcer/internal/generator"
	mock "github.com/stretchr/testify/mock"
)

// Writer is an autogenerated mock type for the Writer type
type Writer struct {
	mock.Mock
}

// Write provides a mock function with given fields: outputDirectory, generated
func (_m *Writer) Write(outputDirectory string, generated *generator.Generated) error {
	ret := _m.Called(outputDirectory, generated)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *generator.Generated) error); ok {
		r0 = rf(outputDirectory, generated)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
