package writer_test

import (
	"github.com/csueiras/reinforcer/internal/generator"
	"github.com/csueiras/reinforcer/internal/writer"
	"github.com/csueiras/reinforcer/internal/writer/filename"
	wio "github.com/csueiras/reinforcer/internal/writer/io"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestWriter_Write(t *testing.T) {
	bop := wio.NewBufferOutputProvider()
	w := writer.New(bop, filename.SnakeCaseStrategy())
	require.NoError(t, w.Write("testing", &generator.Generated{
		Common: `// Code generated by reinforcer, DO NOT EDIT.

package mytestpackage

// Common Code Here
`,
		Constants: `// Code generated by reinforcer, DO NOT EDIT.

package mytestpackage

// Constants Here
`,
		Files: []*generator.GeneratedFile{
			{
				TypeName: "GeneratedService",
				Contents: `// Code generated by reinforcer, DO NOT EDIT.

package mytestpackage

// Proxy Code Here
`,
			},
		},
	}))

	require.Equal(t, `// Code generated by reinforcer, DO NOT EDIT.

package mytestpackage

// Common Code Here
`, bop.Buffers["testing/reinforcer_common.go"].String())
	require.Equal(t, `// Code generated by reinforcer, DO NOT EDIT.

package mytestpackage

// Constants Here
`, bop.Buffers["testing/reinforcer_constants.go"].String())
	require.Equal(t, `// Code generated by reinforcer, DO NOT EDIT.

package mytestpackage

// Proxy Code Here
`, bop.Buffers["testing/generated_service.go"].String())
}
