// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	loader "github.com/csueiras/reinforcer/internal/loader"
	mock "github.com/stretchr/testify/mock"
)

// Loader is an autogenerated mock type for the Loader type
type Loader struct {
	mock.Mock
}

// LoadAll provides a mock function with given fields: path, mode
func (_m *Loader) LoadAll(path string, mode loader.LoadMode) (map[string]*loader.Result, error) {
	ret := _m.Called(path, mode)

	var r0 map[string]*loader.Result
	if rf, ok := ret.Get(0).(func(string, loader.LoadMode) map[string]*loader.Result); ok {
		r0 = rf(path, mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*loader.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, loader.LoadMode) error); ok {
		r1 = rf(path, mode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadMatched provides a mock function with given fields: path, expressions, mode
func (_m *Loader) LoadMatched(path string, expressions []string, mode loader.LoadMode) (map[string]*loader.Result, error) {
	ret := _m.Called(path, expressions, mode)

	var r0 map[string]*loader.Result
	if rf, ok := ret.Get(0).(func(string, []string, loader.LoadMode) map[string]*loader.Result); ok {
		r0 = rf(path, expressions, mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*loader.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, []string, loader.LoadMode) error); ok {
		r1 = rf(path, expressions, mode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
